-- Seed data (local only — runs on `supabase db reset`, never on production).
--
-- The card catalog and store are now owned entirely by migrations, so this file
-- is intentionally empty of data:
--   * cards   — supabase/migrations/0005_cards_laliga_2025.sql (current-season LaLiga)
--   * starter — supabase/migrations/0009_starter_deck.sql (the 55-card "juego básico"
--               flagged is_starter, granted to every new account by handle_new_user)
--   * packs   — supabase/migrations/0008_store_packs.sql
--
-- The old placeholder test cards (the decoded 1995 originals and the `base-*`
-- fillers) were removed: only current-season players are used now.
