// Catalog builder: read the vendored LaLiga snapshot, derive a Super Gol card for
// every player, and write the local catalog SEED. Run: `npm run build:cards`.
//
// The output is supabase/seed_cards.sql — a seed, NOT a migration. The card catalog
// is a dynamic, admin-owned table: on production it is bootstrapped/refreshed by
// importing the admin CSV, so seeding it through the migration ledger would give it
// two sources of truth. This seed exists only so a local `db:reset` comes up with a
// working catalog; a local-only guard (emitted below) keeps it off any hosted DB.
//
// This is an authoring tool: it never runs in the app or the edge function, so it
// is free to read the filesystem. Player photos hotlink virtua-fc's own public
// CDN (see photos.ts), so there is nothing to upload. Row derivation lives in
// rows.ts, shared with the CSV export; the starter deck in data/starter-deck.ts.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { buildRows, loadAbilities, SEASON_TAG, type CardRow, type TmLeague } from './rows'
import { STARTER_IDS } from './data/starter-deck'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..', '..')
const OUT_FILE = join(ROOT, 'supabase', 'seed_cards.sql')

const q = (s: string | null): string => (s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`)
const j = (v: unknown): string => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
const n = (v: number | null): string => (v == null ? 'NULL' : String(v))

// Local-only guard, mirroring seed.sql: refuse to run against anything but the
// local Supabase stack, whose JWT secret is public and fixed (so it can never match
// a hosted project). Keeps the catalog seed off production, where the catalog is
// owned by the admin CSV import instead.
const GUARD = `do $$
declare
  local_jwt_secret constant text := 'super-secret-jwt-token-with-at-least-32-characters-long';
begin
  if current_setting('app.settings.jwt_secret', true) is distinct from local_jwt_secret then
    raise exception 'seed_cards.sql refused to run: this database is not the local Supabase stack'
      using
        detail = 'The card catalog is seeded only locally; on a hosted database it is '
                 'imported through the Admin screen (laliga-2025-cards.csv).',
        hint   = 'Use npm run db:reset (local). A hosted catalog comes from the admin CSV import.';
  end if;
end $$;`

function toSql(rows: CardRow[]): string {
  const header = `-- LaLiga ${SEASON_TAG} player catalog — GENERATED by \`npm run build:cards\`.
-- This is a LOCAL SEED (supabase/seed_cards.sql), NOT a migration. The catalog is a
-- dynamic, admin-owned table: production bootstraps/refreshes it via the admin CSV
-- import, so it is seeded here only for local \`db:reset\`. config.toml runs this
-- BEFORE seed.sql, so the starter flags exist before the dev accounts are created.
-- Source: virtua-fc data/2025/ESP1/teams.json (Transfermarkt rosters + market value).
-- Ability factors are inferred: market value + age -> overall (ported from
-- virtua-fc PlayerValuationService) -> per-position factor split (src/cards).
-- Do NOT hand-edit; edit scripts/cards/ + src/cards/ and re-run. ${rows.length} cards.

`
  const cols =
    '(id, name, full_name, club, club_slug, nationality, birth_date, height_cm, position, cost, rarity, is_starter, abilities, zone_grid, image_url)'
  const values = rows
    .map(
      (r) =>
        `  (${q(r.id)}, ${q(r.name)}, ${q(r.full_name)}, ${q(r.club)}, ${q(r.club_slug)}, ` +
        `${q(r.nationality)}, ${q(r.birth_date)}, ${n(r.height_cm)}, ${q(r.position)}, ` +
        `${r.cost}, ${q(r.rarity)}, false, ${j(r.abilities)}, ${j(r.zone_grid)}, ${q(r.image_url)})`,
    )
    .join(',\n')
  const update =
    'name = excluded.name, full_name = excluded.full_name, club = excluded.club, ' +
    'club_slug = excluded.club_slug, nationality = excluded.nationality, ' +
    'birth_date = excluded.birth_date, height_cm = excluded.height_cm, ' +
    'position = excluded.position, cost = excluded.cost, rarity = excluded.rarity, ' +
    'abilities = excluded.abilities, zone_grid = excluded.zone_grid, image_url = excluded.image_url'
  const insert = `insert into public.cards\n  ${cols}\nvalues\n${values}\non conflict (id) do update set\n  ${update};`
  // Starter deck ("juego básico"): the 55 cards handle_new_user grants to every new
  // account (source of truth: scripts/cards/data/starter-deck.ts). On a hosted DB the
  // same flags arrive via the is_starter column of the admin CSV. Applied as a second
  // pass so the upsert above can leave is_starter out of its conflict-update.
  const starter = `-- Starter deck ("juego básico") — see scripts/cards/data/starter-deck.ts.\nupdate public.cards set is_starter = true where id in (\n  ${STARTER_IDS.map(q).join(',\n  ')}\n);`
  return `${header}${GUARD}\n\n${insert}\n\n${starter}\n`
}

function summarize(rows: CardRow[]): void {
  const byRarity: Record<string, number> = {}
  const byPos: Record<string, number> = {}
  let withPhoto = 0
  const costs: number[] = []
  for (const r of rows) {
    byRarity[r.rarity] = (byRarity[r.rarity] ?? 0) + 1
    byPos[r.position] = (byPos[r.position] ?? 0) + 1
    if (r.image_url) withPhoto++
    costs.push(r.cost)
  }
  costs.sort((a, b) => a - b)
  const median = costs[Math.floor(costs.length / 2)]
  console.log(`\ncards: ${rows.length}`)
  console.log('rarity:', byRarity)
  console.log('position:', byPos)
  console.log(`cost: min ${costs[0]} median ${median} max ${costs[costs.length - 1]}`)
  console.log(`photos mapped: ${withPhoto}/${rows.length} (${((100 * withPhoto) / rows.length).toFixed(1)}%)`)
}

function main() {
  const league: TmLeague = JSON.parse(readFileSync(join(HERE, 'data', 'laliga-2025.json'), 'utf8'))
  // Abilities come from the hand-editable data/abilities.json when present; ids
  // absent from it (e.g. a newly-vendored roster player) fall back to derived.
  const overrides = loadAbilities()
  const hasOverrides = Object.keys(overrides).length > 0
  const missing: string[] = []
  const rows = buildRows(league, hasOverrides ? overrides : undefined, (id) => missing.push(id))
  writeFileSync(OUT_FILE, toSql(rows))
  console.log(`wrote ${rows.length} cards -> ${OUT_FILE.replace(ROOT + '/', '')}`)
  if (!hasOverrides) {
    console.log('note: data/abilities.json absent — using derived abilities. Run `npm run reseed:cards` to create it.')
  } else if (missing.length > 0) {
    console.log(
      `note: ${missing.length} card(s) not in abilities.json — used derived abilities. ` +
        'Run `npm run reseed:cards` to bake them in.',
    )
  }
  summarize(rows)
}

main()
