// Catalog builder: read the vendored LaLiga snapshot, derive a Super Gol card
// for every player, and write an idempotent migration. Run: `npm run build:cards`.
//
// This is an authoring tool: it never runs in the app or the edge function, so it
// is free to read the filesystem. Player photos hotlink virtua-fc's own public
// CDN (see photos.ts), so there is nothing to upload. Row derivation lives in
// rows.ts, shared with the CSV export.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { buildRows, SEASON_TAG, type CardRow, type TmLeague } from './rows'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..', '..')
const OUT_FILE = join(ROOT, 'supabase', 'migrations', '0005_cards_laliga_2025.sql')

const q = (s: string | null): string => (s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`)
const j = (v: unknown): string => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
const n = (v: number | null): string => (v == null ? 'NULL' : String(v))

function toSql(rows: CardRow[]): string {
  const header = `-- LaLiga ${SEASON_TAG} player catalog — GENERATED by \`npm run build:cards\`.
-- Source: virtua-fc data/2025/ESP1/teams.json (Transfermarkt rosters + market value).
-- Ability factors are inferred: market value + age -> overall (ported from
-- virtua-fc PlayerValuationService) -> per-position factor split (src/cards).
-- Do NOT hand-edit; edit scripts/cards/ + src/cards/ and re-run. ${rows.length} cards.

`
  const cols =
    '(id, name, full_name, club, club_slug, nationality, birth_date, height_cm, position, cost, rarity, is_starter, abilities, zone_grid, image_url)'
  const values = rows
    .map(
      (r) =>
        `  (${q(r.id)}, ${q(r.name)}, ${q(r.full_name)}, ${q(r.club)}, ${q(r.club_slug)}, ` +
        `${q(r.nationality)}, ${q(r.birth_date)}, ${n(r.height_cm)}, ${q(r.position)}, ` +
        `${r.cost}, ${q(r.rarity)}, false, ${j(r.abilities)}, ${j(r.zone_grid)}, ${q(r.image_url)})`,
    )
    .join(',\n')
  const update =
    'name = excluded.name, full_name = excluded.full_name, club = excluded.club, ' +
    'club_slug = excluded.club_slug, nationality = excluded.nationality, ' +
    'birth_date = excluded.birth_date, height_cm = excluded.height_cm, ' +
    'position = excluded.position, cost = excluded.cost, rarity = excluded.rarity, ' +
    'abilities = excluded.abilities, zone_grid = excluded.zone_grid, image_url = excluded.image_url'
  return `${header}insert into public.cards\n  ${cols}\nvalues\n${values}\non conflict (id) do update set\n  ${update};\n`
}

function summarize(rows: CardRow[]): void {
  const byRarity: Record<string, number> = {}
  const byPos: Record<string, number> = {}
  let withPhoto = 0
  const costs: number[] = []
  for (const r of rows) {
    byRarity[r.rarity] = (byRarity[r.rarity] ?? 0) + 1
    byPos[r.position] = (byPos[r.position] ?? 0) + 1
    if (r.image_url) withPhoto++
    costs.push(r.cost)
  }
  costs.sort((a, b) => a - b)
  const median = costs[Math.floor(costs.length / 2)]
  console.log(`\ncards: ${rows.length}`)
  console.log('rarity:', byRarity)
  console.log('position:', byPos)
  console.log(`cost: min ${costs[0]} median ${median} max ${costs[costs.length - 1]}`)
  console.log(`photos mapped: ${withPhoto}/${rows.length} (${((100 * withPhoto) / rows.length).toFixed(1)}%)`)
}

function main() {
  const league: TmLeague = JSON.parse(readFileSync(join(HERE, 'data', 'laliga-2025.json'), 'utf8'))
  const rows = buildRows(league)
  writeFileSync(OUT_FILE, toSql(rows))
  console.log(`wrote ${rows.length} cards -> ${OUT_FILE.replace(ROOT + '/', '')}`)
  summarize(rows)
}

main()
