// Catalog builder: read the vendored LaLiga snapshot, derive a Super Gol card
// for every player, and write an idempotent migration. Run: `npm run build:cards`.
//
// This is an authoring tool: it never runs in the app or the edge function, so it
// is free to read the filesystem. Player photos hotlink virtua-fc's own public
// CDN (see photos.ts), so there is nothing to upload.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import type { Abilities } from '../../src/lib/types'
import { ageAt, marketValueToOverall, parseMarketValue } from './valuation'
import { deriveCard } from './factors'
import { clubSlug } from './clubs'
import { photoUrl } from './photos'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..', '..')
const SEASON_TAG = '2526'
const OUT_FILE = join(ROOT, 'supabase', 'migrations', '0005_cards_laliga_2025.sql')

interface TmPlayer {
  id: string
  name: string
  position: string
  nationality?: string[]
  dateOfBirth?: string
  height?: string
  marketValue?: string
}
interface TmClub {
  name: string
  players: TmPlayer[]
}
interface TmLeague {
  clubs: TmClub[]
}

interface CardRow {
  id: string
  name: string
  full_name: string
  club: string
  club_slug: string
  nationality: string | null
  birth_date: string | null
  height_cm: number | null
  position: string
  cost: number
  rarity: string
  abilities: Abilities
  zone_grid: boolean[][]
  image_url: string | null
}

function slugify(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

/** Display surname: last whitespace-separated token, uppercased. */
function surname(fullName: string): string {
  const parts = fullName.trim().split(/\s+/)
  return (parts[parts.length - 1] || fullName).toUpperCase()
}

function parseHeightCm(height: string | undefined): number | null {
  if (!height) return null
  const m = height.replace(',', '.').match(/([\d.]+)/)
  if (!m) return null
  const meters = parseFloat(m[1])
  return isFinite(meters) ? Math.round(meters * 100) : null
}

function parseBirthDate(dob: string | undefined): string | null {
  if (!dob) return null
  const d = new Date(dob)
  return isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10)
}

function buildRows(league: TmLeague): CardRow[] {
  const rows: CardRow[] = []
  const seen = new Set<string>()
  for (const club of league.clubs) {
    const slug = clubSlug(club.name)
    for (const p of club.players ?? []) {
      const isGk = /goal|keeper/i.test(p.position)
      const overall = marketValueToOverall(
        parseMarketValue(p.marketValue),
        ageAt(p.dateOfBirth),
        isGk,
      )
      const derived = deriveCard(p.position, overall)

      let id = `${slugify(p.name)}-${slug}-${SEASON_TAG}`
      if (seen.has(id)) id = `${id}-${p.id}`
      seen.add(id)

      rows.push({
        id,
        name: surname(p.name),
        full_name: p.name,
        club: club.name,
        club_slug: slug,
        nationality: p.nationality?.[0] ?? null,
        birth_date: parseBirthDate(p.dateOfBirth),
        height_cm: parseHeightCm(p.height),
        position: derived.position,
        cost: derived.cost,
        rarity: derived.rarity,
        abilities: derived.abilities,
        zone_grid: derived.zone_grid,
        image_url: photoUrl(p.id),
      })
    }
  }
  return rows
}

const q = (s: string | null): string => (s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`)
const j = (v: unknown): string => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
const n = (v: number | null): string => (v == null ? 'NULL' : String(v))

function toSql(rows: CardRow[]): string {
  const header = `-- LaLiga ${SEASON_TAG} player catalog — GENERATED by \`npm run build:cards\`.
-- Source: virtua-fc data/2025/ESP1/teams.json (Transfermarkt rosters + market value).
-- Ability factors are inferred: market value + age -> overall (ported from
-- virtua-fc PlayerValuationService) -> per-position factor split (scripts/cards).
-- Do NOT hand-edit; edit scripts/cards/ and re-run. ${rows.length} cards.

`
  const cols =
    '(id, name, full_name, club, club_slug, nationality, birth_date, height_cm, position, cost, rarity, is_starter, abilities, zone_grid, image_url)'
  const values = rows
    .map(
      (r) =>
        `  (${q(r.id)}, ${q(r.name)}, ${q(r.full_name)}, ${q(r.club)}, ${q(r.club_slug)}, ` +
        `${q(r.nationality)}, ${q(r.birth_date)}, ${n(r.height_cm)}, ${q(r.position)}, ` +
        `${r.cost}, ${q(r.rarity)}, false, ${j(r.abilities)}, ${j(r.zone_grid)}, ${q(r.image_url)})`,
    )
    .join(',\n')
  const update =
    'name = excluded.name, full_name = excluded.full_name, club = excluded.club, ' +
    'club_slug = excluded.club_slug, nationality = excluded.nationality, ' +
    'birth_date = excluded.birth_date, height_cm = excluded.height_cm, ' +
    'position = excluded.position, cost = excluded.cost, rarity = excluded.rarity, ' +
    'abilities = excluded.abilities, zone_grid = excluded.zone_grid, image_url = excluded.image_url'
  return `${header}insert into public.cards\n  ${cols}\nvalues\n${values}\non conflict (id) do update set\n  ${update};\n`
}

function summarize(rows: CardRow[]): void {
  const overalls = rows.length
  const byRarity: Record<string, number> = {}
  const byPos: Record<string, number> = {}
  let withPhoto = 0
  const costs: number[] = []
  for (const r of rows) {
    byRarity[r.rarity] = (byRarity[r.rarity] ?? 0) + 1
    byPos[r.position] = (byPos[r.position] ?? 0) + 1
    if (r.image_url) withPhoto++
    costs.push(r.cost)
  }
  costs.sort((a, b) => a - b)
  const median = costs[Math.floor(costs.length / 2)]
  console.log(`\ncards: ${overalls}`)
  console.log('rarity:', byRarity)
  console.log('position:', byPos)
  console.log(`cost: min ${costs[0]} median ${median} max ${costs[costs.length - 1]}`)
  console.log(`photos mapped: ${withPhoto}/${overalls} (${((100 * withPhoto) / overalls).toFixed(1)}%)`)
}

function main() {
  const league: TmLeague = JSON.parse(
    readFileSync(join(HERE, 'data', 'laliga-2025.json'), 'utf8'),
  )
  const rows = buildRows(league)
  writeFileSync(OUT_FILE, toSql(rows))
  console.log(`wrote ${rows.length} cards -> ${OUT_FILE.replace(ROOT + '/', '')}`)
  summarize(rows)
}

main()
