// GENERATED by `npm run build:function` from supabase/functions/_src/play-match.ts — do not edit.

// supabase/functions/_src/play-match.ts
import { createClient } from "npm:@supabase/supabase-js@2.47.10";

// src/game/engine/rng.ts
function createRng(seed) {
  let state = seed >>> 0;
  const next = () => {
    state = state + 1831565813 >>> 0;
    let t = state;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
  const int = (n) => Math.floor(next() * n);
  return {
    next,
    int,
    d6: () => int(6) + 1,
    pick: (xs) => xs[int(xs.length)],
    chance: (p) => next() < p
  };
}
function seedFrom(...parts) {
  let h = 2166136261;
  const str = parts.join("|");
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

// src/game/engine/pitch.ts
var COLS = 6;
var ROWS = 5;
var ZONE_MAP = [
  ["PA", "RM", "RM", "RM", "RM", "PA"],
  // row 0 — home's own box
  ["PA", "DL", "DL", "DL", "DL", "PA"],
  // row 1
  ["PA", "MID", "MID", "MID", "MID", "PA"],
  // row 2 — midfield
  ["PA", "DL", "DL", "DL", "DL", "PA"],
  // row 3
  ["PA", "RM", "RM", "RM", "RM", "PA"]
  // row 4 — away's box (home's target)
];
function zoneAt(cell) {
  return ZONE_MAP[cell.row][cell.col];
}
var clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
function makePitch(cell, attacker) {
  const dir = attacker === "home" ? 1 : -1;
  const goalRow = attacker === "home" ? ROWS - 1 : 0;
  const zone = zoneAt(cell);
  return {
    cell,
    zone,
    attacker,
    canShootRM: () => zone === "RM",
    canShootDL: () => zone === "DL",
    step: (d) => makePitch({ col: cell.col, row: clamp(cell.row + dir * d, 0, ROWS - 1) }, attacker),
    toLane: (col) => makePitch({ col: clamp(col, 0, COLS - 1), row: cell.row }, attacker),
    toGoal: () => Math.abs(goalRow - cell.row)
  };
}
var CENTRE_LANE = 2;
function initialPitch(attacker) {
  return makePitch({ col: CENTRE_LANE, row: 2 }, attacker);
}
function laneFor(index) {
  return 1 + (index % 4 + 4) % 4;
}

// src/game/ratings.ts
function abilityValue(card, key) {
  return card.abilities[key] ?? 0;
}
function isGoalkeeper(card) {
  const pos = (card.position ?? "").toLowerCase();
  if (/^(gk|por|pt)/.test(pos)) return true;
  return abilityValue(card, "rf") > 0 || abilityValue(card, "co") > 0;
}
function keeperStats(card) {
  return { rf: abilityValue(card, "rf"), co: abilityValue(card, "co") };
}

// src/game/engine/dice.ts
var TARGET = 10;
function diceForPass(mark, type) {
  if (type === "PD") return 0;
  if (mark === "MH") return 2;
  if (type === "PC") return mark === "SM" || mark === "LIBRE" ? 0 : 1;
  return 1;
}
function passDice(passer, receiver, type) {
  return Math.max(diceForPass(passer, type), diceForPass(receiver, type));
}
function diceForAction(mark, _action) {
  return mark === "MH" ? 2 : 1;
}
function scoreContest(dice, rating) {
  const bonus = dice.length === 1 ? 5 : 0;
  const total = dice.reduce((s, d) => s + d, 0) + bonus + rating;
  const success = dice.length === 0 ? true : total >= TARGET;
  return { dice, total, success };
}
function resolveContest(rng, n, rating) {
  const dice = [];
  for (let i = 0; i < n; i++) dice.push(rng.d6());
  return scoreContest(dice, rating);
}
function contestDice(mark, action) {
  return diceForAction(mark, action);
}

// src/game/engine/marcaje.ts
function afterAnticipacion(success) {
  if (success) return { possession: "defender", carrier: "LIBRE" };
  return { possession: "attacker", carrier: "LIBRE" };
}
function afterRobo(success) {
  if (success) return { possession: "defender", carrier: "MH" };
  return { possession: "attacker", carrier: "LIBRE" };
}
function afterRegate(success) {
  return { possession: "attacker", carrier: success ? "LIBRE" : "MZ" };
}
function forDice(mark) {
  return mark === "LIBRE" ? "SM" : mark;
}

// src/game/engine/actions.ts
function resolvePase(rng, type, passerMark, receiverMark, rating) {
  const n = passDice(forDice(passerMark), forDice(receiverMark), type);
  return resolveContest(rng, n, rating);
}
function resolvePaseHueco(rng, rating) {
  return resolveContest(rng, 2, rating);
}
function resolveRegate(rng, mark, rg) {
  return resolveContest(rng, contestDice(forDice(mark), "RG"), rg);
}
function resolveShot(rng, action, mark, rating) {
  return resolveContest(rng, contestDice(forDice(mark), action), rating);
}

// src/game/engine/interrupt.ts
function resolveAnticipacion(rng, a) {
  return resolveContest(rng, 2, a);
}
function resolveRobo(rng, rb) {
  return resolveContest(rng, 2, rb);
}

// src/game/engine/keeper.ts
function resolveSave(rng, stat) {
  const contest = resolveContest(rng, 2, stat);
  return { contest, saved: contest.success };
}
function isGoal(shotSuccess, saved) {
  return shotSuccess && !saved;
}

// src/game/engine/ai.ts
var TUNING = {
  easy: { finishing: 0.45, press: 0.35, interrupt: 0.45 },
  normal: { finishing: 0.55, press: 0.55, interrupt: 0.6 },
  hard: { finishing: 0.6, press: 0.75, interrupt: 0.78 }
};
function tuning(difficulty) {
  return TUNING[difficulty];
}
function marked(mark) {
  return mark === "MH" || mark === "MZ";
}
function chooseAttack(rng, pitch, mark, carrier, difficulty) {
  const t = tuning(difficulty);
  const dl = abilityValue(carrier, "dl");
  const rg = abilityValue(carrier, "rg");
  if (pitch.canShootRM()) {
    if (mark === "MH" && rng.chance(0.35 + rg * 0.08)) return { kind: "regate" };
    return { kind: "shot", action: "RM" };
  }
  if (pitch.canShootDL()) {
    const shootWeight = t.finishing + dl * 0.1;
    if (mark === "MH" && rng.chance(0.3 + rg * 0.08)) return { kind: "regate" };
    if (rng.chance(Math.min(0.85, shootWeight))) return { kind: "shot", action: "DL" };
    return advanceChoice(rng, mark, carrier);
  }
  if (mark === "MH" && rng.chance(0.3 + rg * 0.08)) return { kind: "regate" };
  return advanceChoice(rng, mark, carrier);
}
function advanceChoice(rng, mark, carrier) {
  const pc = abilityValue(carrier, "pc");
  const pl = abilityValue(carrier, "pl");
  if (marked(mark) && rng.chance(0.2)) {
    return { kind: "hueco", type: pl >= pc ? "PL" : "PC" };
  }
  if (pc === 0 && pl === 0) return { kind: "advance" };
  return { kind: "pase", type: pl > pc ? "PL" : "PC" };
}
function pressAfterMove(rng, current, difficulty) {
  const t = tuning(difficulty);
  if (!rng.chance(t.press)) return current === "LIBRE" ? "SM" : current;
  if (current === "MH") return "MH";
  if (current === "MZ") return "MH";
  return "MZ";
}
function chooseInterrupt(rng, receiverMark, difficulty) {
  const t = tuning(difficulty);
  if (receiverMark === "MZ") return rng.chance(t.interrupt) ? "anticipacion" : "none";
  if (receiverMark === "MH") return rng.chance(t.interrupt) ? "robo" : "none";
  return "none";
}

// src/game/engine/events.ts
function ev(type, side, params = {}, cell) {
  return { type, side, params: cell ? { ...params, cell } : params };
}
function evContest(type, side, opts) {
  return {
    type,
    side,
    params: {
      player: opts.player,
      target: opts.target,
      ability: opts.ability,
      marcaje: opts.marcaje,
      dice: opts.contest.dice,
      total: opts.contest.total,
      success: opts.contest.success,
      cell: opts.cell
    }
  };
}

// src/game/engine/loop.ts
var WIN_MARGIN = 2;
var MAX_POSSESSIONS = 80;
var JUGADA_BUDGET = 10;
var other = (s) => s === "home" ? "away" : "home";
function squadOf(state, side) {
  return side === "home" ? state.home : state.away;
}
function defenderBest(squad, key) {
  return squad.outfield.reduce((best, c) => Math.max(best, abilityValue(c, key)), 0);
}
function pickOther(rng, xs, exclude) {
  if (xs.length <= 1) return xs[0];
  let c = rng.pick(xs);
  while (c === exclude) c = rng.pick(xs);
  return c;
}
function pressReceiver(rng, difficulty) {
  const t = tuning(difficulty);
  if (!rng.chance(t.press)) return "SM";
  return rng.chance(t.press) ? "MH" : "MZ";
}
function applyChoice(state, rng, events, choice) {
  const atkSide = state.attacker;
  const defSquad = squadOf(state, other(atkSide));
  switch (choice.kind) {
    case "advance": {
      state.pitch = state.pitch.step(1);
      state.carrierMark = pressAfterMove(rng, state.carrierMark, state.difficulty);
      return "continue";
    }
    case "regate": {
      const rg = abilityValue(state.carrier, "rg");
      const contest = resolveRegate(rng, state.carrierMark, rg);
      events.push(
        evContest("dribble", atkSide, {
          player: state.carrier.name,
          ability: "rg",
          marcaje: state.carrierMark,
          contest,
          cell: state.pitch.cell
        })
      );
      const outcome = afterRegate(contest.success);
      state.carrierMark = outcome.carrier;
      if (contest.success) state.pitch = state.pitch.step(1);
      return "continue";
    }
    case "pase":
    case "hueco": {
      const type = choice.type;
      const rating = abilityValue(state.carrier, type === "PL" ? "pl" : "pc");
      const receiver = pickOther(rng, squadOf(state, atkSide).outfield, state.carrier);
      const receiverMark = choice.kind === "hueco" ? "LIBRE" : pressReceiver(rng, state.difficulty);
      const contest = choice.kind === "hueco" ? resolvePaseHueco(rng, rating) : resolvePase(rng, type, state.carrierMark, receiverMark, rating);
      if (!contest.success) {
        events.push(
          evContest("turnover", atkSide, {
            player: state.carrier.name,
            ability: type === "PL" ? "pl" : "pc",
            contest,
            cell: state.pitch.cell
          })
        );
        flip(state);
        return "turnover";
      }
      state.carrier = receiver;
      state.carrierMark = receiverMark;
      state.pitch = state.pitch.step(1).toLane(laneFor(squadOf(state, atkSide).outfield.indexOf(receiver)));
      if (choice.kind === "pase" && (receiverMark === "MZ" || receiverMark === "MH")) {
        const decision = chooseInterrupt(rng, receiverMark, state.difficulty);
        if (decision === "anticipacion") {
          const contestA = resolveAnticipacion(rng, defenderBest(defSquad, "a"));
          const res = afterAnticipacion(contestA.success);
          if (res.possession === "defender") {
            events.push(
              evContest("interception", other(atkSide), {
                ability: "a",
                contest: contestA,
                cell: state.pitch.cell
              })
            );
            flip(state);
            return "turnover";
          }
          state.carrierMark = res.carrier;
        } else if (decision === "robo") {
          const contestR = resolveRobo(rng, defenderBest(defSquad, "rb"));
          const res = afterRobo(contestR.success);
          if (res.possession === "defender") {
            events.push(
              evContest("steal", other(atkSide), {
                ability: "rb",
                contest: contestR,
                cell: state.pitch.cell
              })
            );
            flip(state);
            return "turnover";
          }
          state.carrierMark = res.carrier;
        }
      }
      return "continue";
    }
    case "shot": {
      const action = choice.action;
      const rating = abilityValue(state.carrier, action === "RM" ? "rm" : "dl");
      const contest = resolveShot(rng, action, state.carrierMark, rating);
      if (!contest.success) {
        events.push(
          evContest("shot", atkSide, {
            player: state.carrier.name,
            ability: action === "RM" ? "rm" : "dl",
            marcaje: state.carrierMark,
            contest,
            cell: state.pitch.cell
          })
        );
        flip(state);
        return "turnover";
      }
      const keeper = squadOf(state, other(atkSide)).keeper;
      const stat = action === "RM" ? keeperStats(keeper).rf : keeperStats(keeper).co;
      const { contest: saveContest, saved } = resolveSave(rng, stat);
      if (isGoal(true, saved)) {
        events.push(
          evContest("goal", atkSide, {
            player: state.carrier.name,
            ability: action === "RM" ? "rm" : "dl",
            contest,
            cell: state.pitch.cell
          })
        );
        return "goal";
      }
      events.push(
        evContest("save", other(atkSide), {
          player: keeper.name,
          ability: action === "RM" ? "rf" : "co",
          contest: saveContest,
          cell: state.pitch.cell
        })
      );
      flip(state);
      return "turnover";
    }
  }
}
function flip(state) {
  state.attacker = other(state.attacker);
}
function runPossession(state, rng, events, kickoff) {
  const squad = squadOf(state, state.attacker);
  state.pitch = initialPitch(state.attacker);
  state.carrier = rng.pick(squad.outfield);
  state.carrierMark = "SM";
  state.minute = Math.min(120, state.minute + rng.int(4) + 1);
  if (kickoff) {
    events.push(ev("kickoff", state.attacker, { player: state.carrier.name }, state.pitch.cell));
    state.carrier = pickOther(rng, squad.outfield, state.carrier);
  }
  for (let budget = JUGADA_BUDGET; budget > 0; budget--) {
    const choice = chooseAttack(rng, state.pitch, state.carrierMark, state.carrier, state.difficulty);
    const outcome = applyChoice(state, rng, events, choice);
    if (outcome === "goal") {
      if (state.attacker === "home") state.gf++;
      else state.ga++;
      state.attacker = other(state.attacker);
      return { scored: true, kickoff: true };
    }
    if (outcome === "turnover") return { scored: false, kickoff: false };
  }
  flip(state);
  return { scored: false, kickoff: false };
}
function terminated(state) {
  return Math.abs(state.gf - state.ga) >= WIN_MARGIN || state.possessions >= MAX_POSSESSIONS;
}
function runMatch(state, rng) {
  const events = [];
  const minutes = [];
  const stamp = () => {
    while (minutes.length < events.length) minutes.push(state.minute);
  };
  let kickoff = true;
  while (!terminated(state)) {
    const result = runPossession(state, rng, events, kickoff);
    stamp();
    kickoff = result.kickoff;
    state.possessions++;
  }
  events.push(ev("fulltime", "home"));
  stamp();
  return { events, minutes };
}

// src/game/abilities.ts
var ABILITY_META = {
  rb: { abbr: "RB", label: "Robo bal\xF3n" },
  a: { abbr: "A", label: "Anticipaci\xF3n" },
  rc: { abbr: "RC", label: "Remate cabeza" },
  d: { abbr: "D", label: "Desmarque" },
  rg: { abbr: "RG", label: "Regate" },
  v: { abbr: "V", label: "Velocidad" },
  pc: { abbr: "PC", label: "Pase corto" },
  pl: { abbr: "PL", label: "Pase largo" },
  pa: { abbr: "PA", label: "Pase alto" },
  dl: { abbr: "DL", label: "Disparo lejano" },
  rm: { abbr: "RM", label: "Remate" },
  // Goalkeeper ratings — only meaningful on the portero card.
  rf: { abbr: "RF", label: "Reflejos" },
  co: { abbr: "CO", label: "Colocaci\xF3n" }
};
var OUTFIELD_ABILITY_KEYS = [
  "rb",
  "a",
  "rc",
  "d",
  "rg",
  "v",
  "pc",
  "pl",
  "pa",
  "dl",
  "rm"
];
var KEEPER_ABILITY_KEYS = ["rf", "co"];
var ABILITY_ORDER = [
  ...OUTFIELD_ABILITY_KEYS,
  ...KEEPER_ABILITY_KEYS
];

// src/game/engine/format-es.ts
function ability(e) {
  return e.params.ability ? ABILITY_META[e.params.ability].abbr : "";
}
function player(e) {
  return e.params.player ?? "Un jugador";
}
function renderEs(e) {
  const p = player(e);
  switch (e.type) {
    case "kickoff":
      return `Saque desde el centro. Mueve ${p}.`;
    case "pass":
      return `${p} combina con los suyos.`;
    case "dribble":
      return e.params.success ? `${p} se va en el regate (${ability(e)}).` : `${p} lo intenta en el regate pero lo frenan.`;
    case "shot":
      return `${p} dispara (${ability(e)}) y se va fuera.`;
    case "save":
      return `\xA1Parad\xF3n de ${p}! (${ability(e)}).`;
    case "goal":
      return `\xA1GOOOOL de ${p}! (${ability(e)}).`;
    case "interception":
      return `Anticipaci\xF3n (${ability(e)}); corta el bal\xF3n la defensa.`;
    case "steal":
      return `Robo de bal\xF3n (${ability(e)}); recupera la defensa.`;
    case "turnover":
      return `${p} pierde el bal\xF3n.`;
    case "fulltime":
      return "Final del partido.";
  }
}

// src/game/engine/opponent.ts
var OPPONENT_NAMES = {
  easy: "CF Domingueros",
  normal: "Atl\xE9tico Medio",
  hard: "Real Elite CF"
};
var RATING_MEAN = {
  easy: 1,
  normal: 2,
  hard: 3
};
var RATING_MAX = 5;
var OUTFIELD_KEYS = [
  "rb",
  "a",
  "rc",
  "d",
  "rg",
  "v",
  "pc",
  "pl",
  "pa",
  "dl",
  "rm"
];
function sampleRating(rng, mean) {
  const draw = () => mean - 1 + rng.next() * 2;
  const v = Math.round((draw() + draw()) / 2);
  return Math.max(0, Math.min(RATING_MAX, v));
}
function outfieldAbilities(rng, mean) {
  const a = {};
  for (const k of OUTFIELD_KEYS) a[k] = sampleRating(rng, mean);
  return a;
}
function keeperAbilities(rng, mean) {
  return { rf: sampleRating(rng, mean), co: sampleRating(rng, mean) };
}
function generateOpponent(difficulty, rng) {
  const mean = RATING_MEAN[difficulty];
  const outfield = [];
  for (let i = 0; i < 10; i++) {
    outfield.push({
      id: `ai-${difficulty}-${i}`,
      name: `Rival ${i + 1}`,
      position: null,
      abilities: outfieldAbilities(rng, mean)
    });
  }
  const keeper = {
    id: `ai-${difficulty}-gk`,
    name: "Portero rival",
    position: "GK",
    abilities: keeperAbilities(rng, mean)
  };
  return { name: OPPONENT_NAMES[difficulty], outfield, keeper };
}

// src/game/engine/index.ts
var REWARD = { win: 100, draw: 40, loss: 10 };
function resultFor(gf, ga) {
  if (gf > ga) return "win";
  if (gf < ga) return "loss";
  return "draw";
}
function simulateMatch(input) {
  const rng = createRng(input.seed);
  const state = {
    home: input.home,
    away: input.away,
    difficulty: input.difficulty,
    attacker: "home",
    // the human squad kicks off
    pitch: initialPitch("home"),
    carrier: input.home.outfield[0],
    carrierMark: "SM",
    gf: 0,
    ga: 0,
    minute: 0,
    possessions: 0
  };
  const { events, minutes } = runMatch(state, rng);
  const log = events.map((e, i) => ({
    minute: minutes[i] ?? state.minute,
    side: e.side,
    text: renderEs(e),
    type: e.type,
    params: e.params
  }));
  const result = resultFor(state.gf, state.ga);
  return {
    result,
    opponent: input.away.name || OPPONENT_NAMES[input.difficulty],
    goals_for: state.gf,
    goals_against: state.ga,
    coins_awarded: REWARD[result],
    log
  };
}

// src/game/engine/squad.ts
function buildEngineSquad(name, squad, catalog) {
  const byId = new Map(catalog.map((c) => [c.id, c]));
  const starters = squad.slots.filter((s) => s.is_starter).map((s) => byId.get(s.card_id)).filter((c) => Boolean(c)).map((c) => ({ id: c.id, name: c.name, position: c.position, abilities: c.abilities }));
  if (starters.length === 0) throw new Error("your squad has no starters");
  let keeperIdx = starters.findIndex(isGoalkeeper);
  if (keeperIdx < 0) keeperIdx = 0;
  const keeper = starters[keeperIdx];
  const outfield = starters.filter((_, i) => i !== keeperIdx);
  return { name, outfield, keeper };
}

// supabase/functions/_src/play-match.ts
var CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS"
};
var DIFFICULTIES = ["easy", "normal", "hard"];
function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, "Content-Type": "application/json" }
  });
}
Deno.serve(async (req) => {
  var _a;
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS_HEADERS });
  if (req.method !== "POST") return json({ error: "method not allowed" }, 405);
  const url = Deno.env.get("SUPABASE_URL");
  const anonKey = Deno.env.get("SUPABASE_ANON_KEY");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  const authHeader = req.headers.get("Authorization");
  if (!authHeader) return json({ error: "not authenticated" }, 401);
  const userClient = createClient(url, anonKey, {
    global: { headers: { Authorization: authHeader } }
  });
  const { data: auth } = await userClient.auth.getUser();
  const uid = (_a = auth.user) == null ? void 0 : _a.id;
  if (!uid) return json({ error: "not authenticated" }, 401);
  let difficulty = "normal";
  try {
    const body = await req.json();
    if (body && DIFFICULTIES.includes(body.p_difficulty)) difficulty = body.p_difficulty;
  } catch {
  }
  const { data: squadRow, error: squadErr } = await userClient.from("squads").select("id, name, formation, total_cost").order("is_active", { ascending: false }).limit(1).maybeSingle();
  if (squadErr) return json({ error: squadErr.message }, 400);
  if (!squadRow) return json({ error: "you have no squad yet" }, 400);
  const { data: slots, error: slotErr } = await userClient.from("squad_slots").select("card_id, slot, is_starter").eq("squad_id", squadRow.id).order("slot", { ascending: true });
  if (slotErr) return json({ error: slotErr.message }, 400);
  const { data: catalog, error: catErr } = await userClient.from("cards").select("*");
  if (catErr) return json({ error: catErr.message }, 400);
  const squad = { ...squadRow, slots: slots ?? [] };
  const cards = catalog ?? [];
  let home;
  try {
    home = buildEngineSquad(squad.name || "Tu equipo", squad, cards);
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : "invalid squad" }, 400);
  }
  const seed = seedFrom(Date.now(), difficulty, squad.id);
  const away = generateOpponent(difficulty, createRng(seedFrom(seed, "opponent")));
  const outcome = simulateMatch({ home, away, difficulty, seed });
  const byId = new Map(cards.map((c) => [c.id, c]));
  const strength = squad.slots.filter((s) => s.is_starter).reduce((sum, s) => {
    var _a2;
    return sum + (((_a2 = byId.get(s.card_id)) == null ? void 0 : _a2.cost) ?? 0);
  }, 0);
  const adminClient = createClient(url, serviceKey);
  const { data: recorded, error: recErr } = await adminClient.rpc("record_match", {
    p_uid: uid,
    p_opponent: outcome.opponent,
    p_difficulty: difficulty,
    p_result: outcome.result,
    p_gf: outcome.goals_for,
    p_ga: outcome.goals_against,
    p_squad_strength: strength,
    p_log: outcome.log
  });
  if (recErr) return json({ error: recErr.message }, 500);
  return json({
    ...outcome,
    coins_awarded: recorded.coins_awarded
  });
});
